services:
  # nginxのコンテナ
  amazonlinux2023:
    container_name: 'al2023'
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes: #ホストにあるファイルをマウント
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/soundhouse.conf:/etc/nginx/conf.d/soundhouse.conf
      - ./docker/nginx/soundhouse/:/etc/nginx/conf.d/soundhouse/
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./docker/nginx/fastcgi_params2:/etc/nginx/fastcgi_params2
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
      - ./docker/nginx/log/:/var/log/nginx/
      - ./sfcc-sh-php:/var/www/html/
      - ./sfcc-sh-php:/soundhouse/
    tty: true # ← これがないとコンテナにログインできない
    ports:
      - 80:80 #80ポート
      - 443:443 #443ポート
    environment:
      TZ: Asia/Tokyo

  #PHPのコンテナ
  php:
    container_name: 'php'
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    command: php-fpm -F
    volumes:
      - ./sfcc-sh-php:/var/www/html/
      - ./sfcc-sh-php:/soundhouse/
      - ./docker/php/log:/var/log/php-fpm
      - ./docker/php/php.ini:/etc/php.ini
    tty: true
    environment:
      TZ: Asia/Tokyo

  # Postgresのコンテナ
  # postgres:
  #   container_name: 'postgres_pta'
  #   build:
  #     dockerfile: ./docker/postgres/Dockerfile
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - PGDATA:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: 'admin'
  #     POSTGRES_PASSWORD: 'admin'
  #     POSTGRES_INITDB_ARGS: '--locale=ja_JP.utf8'
  #     POSTGRES_DB: 'postdb'
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   restart: always

  #phppgadminのコンテナ
  # pgadmin4:
  #   image: dpage/pgadmin4:8
  #   container_name: 'pgadmin4'
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./postgresql/pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@logw.jp
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   hostname: pgadmin4
  #   depends_on:
  #     - postgres
  #   restart: always

  # redisのコンテナ
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - './docker/redis/data/:/data/'
      - './docker/redis/log/:/log/'
      - './docker/redis/redis.conf:/etc/redis/redis.conf'
    command: ['redis-server', '/etc/redis/redis.conf']
    environment:
      TZ: Asia/Tokyo

volumes:
  PGDATA:
